apiVersion: v1
kind: Secret
metadata:
  name: {{ include "automate-it.fullname" . }}-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5ob21lLmdscm9sYW5kLmNvbSI6IHsKICAgICAgImF1dGgiOiAiYzNGc1kyaGhkQ3R2WTNBNlZrbzBSbEEzUkZoWlJEVlVXa2MzVFZOU1ZsY3lXRWhLUkZOQlYwVklPRXBLVDFKV1RUVTRPRFUxTkU5T1dFUk1URXhQTlRoU1ExZEdTMWhSVGxwUVVRPT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
