apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automate-it
spec:
  destination:
    name: in-cluster
    namespace: automate-it
    server: https://kubernetes.default.svc
  source:
    path: deploy/helm
    repoURL: https://github.com/glroland/classify_incidents.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
