apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "automate-it.fullname" . }}
  labels:
    {{- include "automate-it.labels" . | nindent 4 }}
immutable: false
data:
  OPENAI_BASE_URL: "http://my-llama-stack.my-llama-stack.svc:8080/v1"
  OPENAI_API_KEY: "not_provided"
  OPENAI_MODEL: "granite4"
  AUTOMATE_AGENT_URL: "http://{{ .Release.Name }}-automate-agent.automate-it.svc:8080/mcp"
  API_TIMEOUT: "60"
  PROMPTS_LOCATION: "./prompts/"
  OBJECT_STORAGE_URL: "https://eclipse.home.glroland.com:9000"
  OBJECT_STORAGE_BUCKET: "classify-incidents"
