apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "automate-it.fullname" . }}
  labels:
    {{- include "automate-it.labels" . | nindent 4 }}
immutable: false
data:
  OPENAI_BASE_URL: "http://my-llama-stack.my-llama-stack.svc:8080/v1"
  OPENAI_API_KEY: "not_provided"
  OPENAI_MODEL: "granite4"
  AUTOMATE_AGENT_URL: "http://{{ .Release.Name }}-automate-agent.automate-it.svc:8080/mcp"
  SERVICE_NOW_INSTANCE: ""
  SERVICE_NOW_USERNAME: ""
  SERVICE_NOW_PASSWORD: ""
  API_TIMEOUT: "60"
  PROMPTS_LOCATION: "./prompts/"
  OBJECT_STORAGE_URL: ""
  OBJECT_STORAGE_ACCESS_KEY: ""
  OBJECT_STORAGE_SECRET_KEY: ""
  OBJECT_STORAGE_BUCKET: ""
