apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "automate-it.fullname" . }}
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Release.Name }}-webapp"}]'
  labels:
    app.kubernetes.io/part-of: "{{ .Release.Name }}-automate-it"
    {{- include "automate-it.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "automate-it.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "automate-it.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.image.usePullSecret }}
      imagePullSecrets:
      - name: automate-it-pull-secret
      {{- end }}
      {{ if eq .Values.global.useServiceAccount true }}
      serviceAccountName: {{ include "automate-it.fullname" . }}
      {{ end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}{{ .Values.image.name }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.image.port }}
          env:
            - name: LLAMA_STACK_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "automate-it.fullname" . }}
                  key: LLAMA_STACK_URL
            - name: OPENAI_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "automate-it.fullname" . }}
                  key: OPENAI_BASE_URL
            - name: MODEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "automate-it.fullname" . }}
                  key: MODEL
            - name: AGENT_ASKSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "automate-it.fullname" . }}
                  key: AGENT_ASKSQL_URL
            - name: OPENAI_API_KEY
              value: "nokeyneeded"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
