apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"app"}]'
  labels:
    app: webapp
    app.kubernetes.io/component: webapp
    app.kubernetes.io/instance: webapp
    app.kubernetes.io/name: webapp
    app.kubernetes.io/part-of: automate-it
  name: {{ include "automate-it.fullname" . }}
spec:
  port:
    targetPort: {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ include "automate-it.fullname" . }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
