apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "automate-it.fullname" . }}
  labels:
    {{- include "automate-it.labels" . | nindent 4 }}
immutable: false
data:
  OPENAI_BASE_URL: "http://my-llama-stack.my-llama-stack.svc:8080/v1"
  OPENAI_API_KEY: "not_provided"
  PLANNING_MODEL: "oopenai/gpt-5"
  JUDGE_PLAN_MODEL: "anthropic/claude-3-7-sonnet-20250219"
  CODING_MODEL: "anthropic/claude-3-7-sonnet-20250219"
  WORK_DIR: "/tmp"
  KNOWLEDGE_ENVIRONMENT_URL: "https://raw.githubusercontent.com/glroland/automate-it/refs/heads/main/knowledge/environment.md"
