apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "automate-it.fullname" . }}
  labels:
    {{- include "automate-it.labels" . | nindent 4 }}
immutable: false
data:
  OPENAI_BASE_URL: "http://my-llama-stack.my-llama-stack.svc:8080/v1"
  OPENAI_API_KEY: "not_provided"
  PLANNING_MODEL: "openai/gpt-5"
  JUDGE_PLAN_MODEL: "claude/sonnet"
  CODING_MODEL: "claude/sonnet"
  WORK_DIR: "/tmp"
