apiVersion: v1
kind: Service
metadata:
  name: {{ include "automate-it.fullname" . }}
  labels:
    {{- include "automate-it.labels" . | nindent 4 }}
spec:
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
  internalTrafficPolicy: Cluster
  type: {{ .Values.service.type }}
  sessionAffinity: None
  selector:
    {{- include "automate-it.selectorLabels" . | nindent 4 }}
